### ISSUE TITLE
Issue with Memory leak in CS2?

### ISSUE THREAD

**Issue by clausdk** [1zc/CS2-Pterodactyl#23]
It seems there's a memory leak in cs2:
https://github.com/ValveSoftware/csgo-osx-linux/issues/3550

Anyone else aware of this?

**Comment by 1zc** [comment]
Not seeing any mem leak issues on my servers anymore - any chance this could be due to specific mods you may have installed?

**Comment by JMorell** [comment]
Valve fixed this memory leak.

**Comment by ghostt187** [comment]
it has been fixed

**Comment by clausdk** [comment]
![image](https://github.com/1zc/CS2-Pterodactyl/assets/14122023/2204500a-e938-49c6-be6b-45271a3e828c)

for me its still happening... after 1-2 hour it starts using up 3-4 gb ram, even with only a few players on it.

**Comment by clausdk** [comment]
![image](https://github.com/1zc/CS2-Pterodactyl/assets/14122023/4f4272aa-0df8-47a6-91aa-dc6c89b42ae5)

Seems it's still happening to me... after 2-3 hours it's going up to 3-4 gb ram.
